### ISSUE TITLE
ValueError: invalid literal for int() with base10

### ISSUE THREAD

**Issue by luis-vera** [NVIDIA/flowtron#102]
Hi:

When I execute: **python train.py -c config.json -p train_config.output_directory=outdir data_config.use_attn_prior=1** the error message was:

Traceback (most recent call last):
  File "train.py", line 348, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 229, in train
    train _loader, valset, collate_fn = prepare_dataloaders(
  File "train.py", line 59, in prepare_dataloaders
    trainset = Data(data_config['training_files'],
  File "C:\Users\luisv\Documents\flowtron\data.py", line 71, in __init__
    self.speaker_ids = self.create_speaker_lookup_table(self.audiopaths_and_text)
  File "C:\Users\luisv\Documents\flowtron\data.py", line 106, in create_speaker_lookup_table
    d = {int(speaker_ids[i]): i for i in range(len(speaker_ids))}
  File "C:\Users\luisv\Documents\flowtron\data.py", line 106, in <dictcomp>
    d = {int(speaker_ids[i]): i for i in range(len(speaker_ids))}
ValueError: invalid literal for int() with base 10: '"A chain fixed to staples at his back passed round his chest under his arms, and was padlocked on the left side;"'

I am using LJSpeech from scratch in Windows 10. I was searching why this error appears and the forum say because I am trying to convert a string in a integer. I am just using Flowtron a couple a days ago and I haven't done any modifications to the original code.

Thanks a lot

**Comment by rafaelvalle** [comment]
it's an issue with your filelist. it must be structured as three "|" separate columns including audiopath|transcription|speaker_id

**Comment by luis-vera** [comment]
Hi Rafael. A have a question about it because I am using LJSpeech and text files that I got from metadata.csv have th e following structure: **audioname|text|normalized text**. 

I would like to know what **speaker_id** is. I only guess It's a integer value so if I have only one speaker for whole audio. Should I put a 0 or 1?

Thanks a lot.

**Comment by rafaelvalle** [comment]
change the structure to be audiopath|normalized text| 0
speaker id is an integer that represents the speaker id

**Comment by rafaelvalle** [comment]
closing due to inactivity.
