### ISSUE TITLE
KeyError: 'iteration' when training using a pre-trained model

### ISSUE THREAD

**Issue by ghwn** [NVIDIA/flowtron#23]
Hi,

I am getting this error whenever I try [this step](https://github.com/NVIDIA/flowtron#training-using-a-pre-trained-model) to train my model using the pre-trained Flowtron LJS model that you publish.

```
$ python train.py -c config.json -p train_config.ignore_layers=["speaker_embedding.weight"] train_config.checkpoint_path="models/flowtron_ljs.pt"
/home/lim/.anaconda3/envs/flowtron/lib/python3.6/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
train_config.ignore_layers=[speaker_embedding.weight]
ignore_layers=[speaker_embedding.weight]
train_config.checkpoint_path=models/flowtron_ljs.pt
checkpoint_path=models/flowtron_ljs.pt
{'train_config': {'output_directory': 'outdir', 'epochs': 10000000, 'learning_rate': 0.0001, 'weight_decay': 1e-06, 'sigma': 1.0, 'iters_per_checkpoint': 5000, 'batch_size': 1, 'seed': 1234, 'checkpoint_path': 'models/flowtron_ljs.pt', 'ignore_layers': '[speaker_embedding.weight]', 'include_layers': ['speaker', 'encoder', 'embedding'], 'warmstart_checkpoint_path': '', 'with_tensorboard': True, 'fp16_run': False}, 'data_config': {'training_files': 'filelists/ljs_audiopaths_text_sid_train_filelist.txt', 'validation_files': 'filelists/ljs_audiopaths_text_sid_val_filelist.txt', 'text_cleaners': ['flowtron_cleaners'], 'p_arpabet': 0.5, 'cmudict_path': 'data/cmudict_dictionary', 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'mel_fmin': 0.0, 'mel_fmax': 8000.0, 'max_wav_value': 32768.0}, 'dist_config': {'dist_backend': 'nccl', 'dist_url': 'tcp://localhost:54321'}, 'model_config': {'n_speakers': 1, 'n_speaker_dim': 128, 'n_text': 185, 'n_text_dim': 512, 'n_flows': 2, 'n_mel_channels': 80, 'n_attn_channels': 640, 'n_hidden': 1024, 'n_lstm_layers': 2, 'mel_encoder_n_hidden': 512, 'n_components': 0, 'mean_scale': 0.0, 'fixed_gaussian': True, 'dummy_speaker_embedding': False, 'use_gate_layer': True}}
> got rank 0 and world size 1 ...
Traceback (most recent call last):
  File "train.py", line 300, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 190, in train
    optimizer, ignore_layers)
  File "train.py", line 107, in load_checkpoint
    iteration = checkpoint_dict['iteration']
KeyError: 'iteration'
```

Of course I downloaded the `flowtron_ljs.pt` into `models` directory and followed [your setup guide](https://github.com/NVIDIA/flowtron#setup).

```
$ git clone https://github.com/NVIDIA/flowtron.git
$ cd flowtron
$ git submodule update --init; cd tacotron2; git submodule update --init

$ conda create -n flowtron python=3.6
$ conda activate flowtron
$ conda install pytorch
$ pip install -r requirements.txt
$ pip install numpy~=1.15.0   # because numba requires "numpy>=1.15"
```

As a result the list of my anaconda packages is:
```
$ conda list
# packages in environment at /home/lim/.anaconda3/envs/flowtron:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
audioread                 2.1.8                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py36_0  
cffi                      1.14.0           py36he30daa8_1  
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
inflect                   0.2.5                    pypi_0    pypi
intel-openmp              2020.1                      217  
joblib                    0.15.1                   pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
librosa                   0.6.0                    pypi_0    pypi
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.32.1                   pypi_0    pypi
matplotlib                2.1.0                    pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.15           py36ha843d7b_0  
mkl_random                1.1.0            py36hd6b4f25_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.9.0            py36hfd86e86_0  
numba                     0.49.1                   pypi_0    pypi
numpy                     1.15.4                   pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
pillow                    7.1.2                    pypi_0    pypi
pip                       20.0.2                   py36_3  
protobuf                  3.12.1                   pypi_0    pypi
pycparser                 2.20                       py_0  
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.4.0           cuda101py36h02f0884_0  
pytz                      2020.1                   pypi_0    pypi
readline                  8.0                  h7b6447c_0  
resampy                   0.2.2                    pypi_0    pypi
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.0.0                    pypi_0    pypi
setuptools                46.4.0                   py36_0  
six                       1.14.0                   py36_0  
sqlite                    3.31.1               h62c20be_1  
tensorboardx              2.0                      pypi_0    pypi
threadpoolctl             2.0.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
unidecode                 1.0.22                   pypi_0    pypi
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3
```

Is there something I missed? thank you.

**Comment by adrianastan** [comment]
The pre-trained model contains only the state_dict, not the entire model structure. Use the `"warmstart_checkpoint_path"` in the config.json instead of `"checkpoint_path"`.

**Comment by ghwn** [comment]
@adrianastan It's working very well! thank you

**Comment by serg06** [comment]
Note that `"checkpoint_path"` and `"warmstart_checkpoint_path"` work very differently:

- When using `"checkpoint_path"`, the code ignores layers in `"ignore_layers"`.
- When using `"warmstart_checkpoint_path"`,
  - Before commit `b485eec01849e2589c09f9f1141a13fbe0984028`: The code includes layers in `"include_layers"` and ignores the rest.
  - After commit `b485eec01849e2589c09f9f1141a13fbe0984028`: The code includes all layers.
