### ISSUE TITLE
Warmstart using Tacotron 2

### ISSUE THREAD

**Issue by Dimonovez** [NVIDIA/flowtron#56]
I want train Flowtron on LJSpeech using Tacotron 2 checkpoint.  I get the following error :
```
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 186, in train
    model = warmstart(warmstart_checkpoint_path, model, include_layers)
  File "train.py", line 100, in warmstart
    model.load_state_dict(model_dict)
  File "/home/dazenkov/dazenkov/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Flowtron:
        size mismatch for embedding.weight: copying a param with shape torch.Size([148, 512]) from checkpoint, the shape in current model is torch.Size([185, 512]).
```
Of course,I have commented out [these rows](https://github.com/NVIDIA/flowtron/blob/master/train.py#L96)
My config:
```
"train_config": {
        "output_directory": "/raid/flowtron/flow_1/flowtron_ljs",
        "epochs": 1000,
        "learning_rate": 1e-4,
        "weight_decay": 1e-6,
        "sigma": 1.0,
        "iters_per_checkpoint": 5000,
        "batch_size": 2,
        "seed": 1234,
        "checkpoint_path": "",
	"ignore_layers": [],
        "include_layers": ["encoder", "embedding"],
        "warmstart_checkpoint_path": "/raid/flowtron/tacotron2/tacotron2_statedict.pt",
	"with_tensorboard": true,
        "fp16_run": false
    }
...
"model_config": {
        "n_speakers": 1,
        "n_speaker_dim": 128,
        "n_text": 185,
        "n_text_dim": 512,
        "n_flows": 1,
        "n_mel_channels": 80,
        "n_attn_channels": 640,
        "n_hidden": 1024,
        "n_lstm_layers": 2,
        "mel_encoder_n_hidden": 512,
        "n_components": 0,
        "mean_scale": 0.0,
        "fixed_gaussian": true,
        "dummy_speaker_embedding": false,
        "use_gate_layer": true
    } 
```
I download tacotron2_statedict.pt from [this link](https://drive.google.com/file/d/1c5ZTuT7J08wLUoVZ2KkUs_VdZuJ86ZqA/view?usp=sharing) (from Tacotron 2 repo).
Why embedding size different? Or I misunderstood how to use tacotron2 statedict. Thank you!

**Comment by adrianastan** [comment]
You need to change `n_text=148` to match the number of text tokens used in the Tacotron2 model

**Comment by Dimonovez** [comment]
Thanks @adrianastan. And next I face with that error https://github.com/NVIDIA/flowtron/issues/20#issuecomment-632974583. And I really want to use Tacotron 2 checkpoint (not using pre-trained LJS Flowtron model). What I should do in that case?

**Comment by adrianastan** [comment]
Check that the files in `text/` folder are similar to the ones in the Tacotron2 -- especially those referring to the symbols list. Also check that the text cleaners are ok.

**Comment by Dimonovez** [comment]
@adrianastan thanks for your help!
