### ISSUE TITLE
Error running train.py: 'lengths' argument should be a 1D CPU int64 tensor

### ISSUE THREAD

**Issue by serg06** [NVIDIA/flowtron#86]
Hello, I'm trying to train the pre-trained model, but training fails.

System:

- Ubuntu 18.04 LTS
- Python 3.6 (Anaconda)

This is my train command:

```
python train.py \
    -c config.json \
    -p train_config.ignore_layers=["speaker_embedding.weight"] \
    train_config.warmstart_checkpoint_path="models/flowtron_ljs.pt" \
    train_config.fp16=true
```

(I have not changed `config.json`.)

And this is the error:

```
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 227, in train
    mel, speaker_vecs, text, in_lens, out_lens)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/serguei/repo/flowtron/flowtron.py", line 576, in forward
    text = self.encoder(text, in_lens)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/serguei/repo/flowtron/flowtron.py", line 323, in forward
    x = nn.utils.rnn.pack_padded_sequence(x, in_lens, batch_first=True)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

**Comment by rafaelvalle** [comment]
just convert in_lens to cpus in_lens.cpu()
you'll probably get another error with respect to lens somewhere else in
the code. the solution is the same.

**Comment by serg06** [comment]
@rafaelvalle thanks for the reply.

This is the problem line btw:
```
z, log_s_list, gate_pred, attn, mean, log_var, prob = model(mel, speaker_vecs, text, in_lens, out_lens)
```

I tried that changing `in_lens` to `in_lens.cpu()` and got another error on the same line:

```
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 227, in train
    mel, speaker_vecs, text, in_lens.cpu(), out_lens)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/serguei/repo/flowtron/flowtron.py", line 591, in forward
    mask = ~get_mask_from_lengths(in_lens)[..., None]
  File "/home/serguei/repo/flowtron/flowtron.py", line 33, in get_mask_from_lengths
    mask = (ids < lengths.unsqueeze(1)).byte()
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/tensor.py", line 27, in wrapped
    return f(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

So I tried changing everything to `.cpu()`:

```
model(mel.cpu(), speaker_vecs.cpu(), text.cpu(), in_lens.cpu(), out_lens.cpu())
```

and got another error on the same line:

```
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 227, in train
    mel, speaker_vecs.cpu(), text.cpu(), in_lens.cpu(), out_lens.cpu())
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/serguei/repo/flowtron/flowtron.py", line 574, in forward
    speaker_vecs = self.speaker_embedding(speaker_vecs)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Input, output and indices must be on the current device
```

**Comment by rafaelvalle** [comment]
It should be enough just to change  this line such that "in_lens.cpu()"
  File "/home/serguei/repo/flowtron/flowtron.py", line 323, in forward
    x = nn.utils.rnn.pack_padded_sequence(x, in_lens, batch_first=True)

**Comment by serg06** [comment]
After changing that line, I got the same error at `flowtron.py` line 451:

<description>
<summary>RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor</summary>

```
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    train(n_gpus, rank, **train_config)
  File "train.py", line 227, in train
    mel, speaker_vecs, text, in_lens, out_lens)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/serguei/repo/flowtron/flowtron.py", line 594, in forward
    mel, encoder_outputs, mask, out_lens)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/serguei/repo/flowtron/flowtron.py", line 471, in forward
    ids, original_ids, lens, mel0, self.attention_lstm)
  File "/home/serguei/repo/flowtron/flowtron.py", line 451, in run_padded_sequence
    padded_data = nn.utils.rnn.pack_padded_sequence(padded_data, lens)
  File "/home/serguei/anaconda3/envs/flowtron/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
```

</description>

which I fixed by changing `lens` to `lens.cpu()`.

Then I ran into #12, which I was able to fix [thanks to your comment](https://github.com/NVIDIA/flowtron/issues/12#issuecomment-629837269)

Now it seems to be working! Thanks @rafaelvalle
