### ISSUE TITLE
RuntimeError: transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure

### ISSUE THREAD

**Issue by serg06** [NVIDIA/flowtron#93]
## System:

- Windows 10

- RTX 3080

- Python 3.6 with PyTorch CUDA 11.0

## Problem:

Whenever I try to run `train.py`, it runs for a few epochs, then I run into the issue stated in the title:

```
Traceback (most recent call last):
  File "C:/repo/flowtron-custom/train.py", line 425, in <module>
    train(n_gpus, rank, **train_config)
  File "C:/repo/flowtron-custom/train.py", line 336, in train
    loss.backward()
  File "C:\Users\Serguei\anaconda3\envs\flowtron-nightly-36\lib\site-packages\torch\tensor.py", line 233, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\Serguei\anaconda3\envs\flowtron-nightly-36\lib\site-packages\torch\autograd\__init__.py", line 146, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure
```

Funnily enough, when I simply remove the `loss.backwards()` line, it stops breaking and runs perfectly.

### Nvidia drivers:
- 457.51 (latest as of Dec 8 2020)
- 465.12 (beta drivers for WSL 2)

### Input data:
- My own data
- LJSpeech

### Batch size:
- 1
- 4

### Commits
- a5a8ef39def9ddf5916ae1603e76fdd113cfa6c7 (Dec 8 2020)
- fe14d3a725b68a22e8e431c6674b2a9cb78b87d6 (Sept 24 2020)

### PyTorch/CUDA configs:
- `os.environ['CUDA_LAUNCH_BLOCKING'] = '1'`
- `torch.cudnn.enabled = False`

### Python versions:
- 3.8
- 3.7
- 3.6

### PyTorch versions:
- 1.7.0 with CUDA 11.0, cuDNN 8.0.4
- 1.8.0 nightly build (12/07) with CUDA 11.0, cuDNN 8.0.4
- 1.7.1 with CUDA 11.0, cuDNN 8.0.5

### FP16:
- Enabled
- Disabled

## What worked?

The only thing that worked to solve the issue was `os.environ['CUDA_LAUNCH_BLOCKING'] = '1'`, but it also slowed the training down by a lot, so it's a pretty awful solution.

**Comment by serg06** [comment]
Just tested this on an RTX 3080 TI with CUDA 10.1, same issue, and same fix worked.

**Comment by serg06** [comment]
Just tried sticking my RTX 3080 in a Ubuntu machine, and the training works perfectly!

So the problem only happens on Windows.

**Comment by kevjshih** [comment]
That's great to hear! I don't believe we've ever tried to run on anything other than Linux so I'd recommend sticking to your working setup if possible.

**Comment by gloriouskilka** [comment]
> Just tested this on an RTX 2080 TI with CUDA 10.1, same issue, and same workaround worked (but made training much slower.)

@serg06, could be please tell, have you ~measured the deceleration due to CUDA_LAUNCH_BLOCKING?
That is common sense that blocking calls will be slower, but I'm not sure if I should move to Ubuntu because of that right now

**Comment by serg06** [comment]
> > Just tested this on an RTX 2080 TI with CUDA 10.1, same issue, and same workaround worked (but made training much slower.)
> 
> @serg06, could be please tell, have you ~measured the deceleration due to CUDA_LAUNCH_BLOCKING?
> That is common sense that blocking calls will be slower, but I'm not sure if I should move to Ubuntu because of that right now
> 
> Update: Google colab's V100 with tensor cores under Ubuntu is 3-5 times faster than gtx1080 on Windows, no more measurements needed :)

Good to hear :)

But to answer your question, it was 3-5 times slower with `CUDA_LAUNCH_BLOCKING` enabled. Ubuntu was definitely worth it.

**Comment by rafaelvalle** [comment]
closing due to inactivity.
